# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
id_1:
  ID: 11
  Return_Delay_Time: 0
  Operating_Mode: 0
#  Position_P_Gain: 400
#  Position_I_Gain: 200
#  Position_D_Gain: 50
#  Profile_Velocity: 200
#  Profile_Acceleration: 50
  
id_2:
  ID: 12
  Return_Delay_Time: 0
  Operating_Mode: 0


id_3:
  ID: 13
  Return_Delay_Time: 0
  Operating_Mode: 0

id_4:
  ID: 21
  Return_Delay_Time: 0
  Operating_Mode: 0

id_5:
  ID: 22
  Return_Delay_Time: 0
  Operating_Mode: 0

id_6:
  ID: 23
  Return_Delay_Time: 0
  Operating_Mode: 0

id_7:
  ID: 31
  Return_Delay_Time: 0
  Operating_Mode: 0

id_8:
  ID: 32
  Return_Delay_Time: 0
  Operating_Mode: 0

id_9:
  ID: 33
  Return_Delay_Time: 0
  Operating_Mode: 0

id_10:
  ID: 41
  Return_Delay_Time: 0
  Operating_Mode: 0

id_11:
  ID: 42
  Return_Delay_Time: 0
  Operating_Mode: 0

id_12:
  ID: 43
  Return_Delay_Time: 0
  Operating_Mode: 0

id_13:
  ID: 51
  Return_Delay_Time: 0
  Operating_Mode: 0

id_14:
  ID: 52
  Return_Delay_Time: 0
  Operating_Mode: 0

id_15:
  ID: 53
  Return_Delay_Time: 0
  Operating_Mode: 0

id_16:
  ID: 61
  Return_Delay_Time: 0
  Operating_Mode: 0

id_17:
  ID: 62
  Return_Delay_Time: 0
  Operating_Mode: 0

id_18:
  ID: 63
  Return_Delay_Time: 0
  Operating_Mode: 0

id_19:
  ID: 71
  Return_Delay_Time: 0
  Operating_Mode: 0

id_20:
  ID: 72
  Return_Delay_Time: 0
  Operating_Mode: 0

id_21:
  ID: 73
  Return_Delay_Time: 0
  Operating_Mode: 0